class Book {
  String id;
  String typeId;
  String types;
  String name;
  DateTime date;
  String imgUrl;
  num score;
  num rating;
  String review;
  num height;

  Book(
    this.id,
    this.typeId,
    this.types,
    this.name,
    this.date,
    this.imgUrl,
    this.score,
    this.rating,
    this.review,
    this.height,
  );

  static List<Book> generateBooks() {
    return [
      Book(
        '30',
        '11',
        'Thiếu nhi',
        'Bạn Tôi Là Người Ngoài Hành Tinh',
        DateTime(2019, 3, 23),
        'assets/images/sach30.jpg',
        6.0,
        600,
        'Một hôm, lớp học của hai cô bé Manju và Yoko xuất hiện một bạn học sinh mới, điều kỳ lạ là cậu tạ nói mình đến từ một hành tinh xa xôi ngoài vũ trụ. Mọi người rất ngạc nhiên, chẳng ai biết cậu ta định làm gì nữa. Bị tò mò thôi thúc, Manju và Yoko quyết định làm thân với cậu học sinh mới. để rồi từ đó hai cô bé khám phá ra một thế giới thật khác với bao điều lạ lẫm, và cùng nhau, họ đã học được những bài học quan trọng về tình bạn, sự quan tâm, sẻ chia cũng như sức mạnh diệu kỳ của trí tưởng tượng.',
        220.0,
      ),
      Book(
        '31',
        '9',
        'Tâm ly',
        'Tâm Lý Học Tội Phạm - Phác Họa Chân Dung Kẻ Phạm Tội',
        DateTime(2019, 3, 23),
        'assets/images/sach31.jpg',
        6.1,
        610,
        'Tội phạm, nhất là những vụ án mạng, luôn là một chủ đề thu hút sự quan tâm của công chúng, khơi gợi sự hiếu kỳ của bất cứ ai. Một khi đã bắt đầu theo dõi vụ án, hẳn bạn không thể không quan tâm tới kết cục, đặc biệt là cách thức và động cơ của kẻ sát nhân, từ những vụ án phạm vi hẹp cho đến những vụ án làm rúng động cả thế giới.',
        220.0,
      ),
      Book(
        '32',
        '9',
        'Tâm lý',
        'Tâm Lý Học Tội Phạm - Tập 2',
        DateTime(2019, 3, 23),
        'assets/images/sach32.jpg',
        6.2,
        620,
        'Giờ đây, với cái nhìn sâu sắc hơn tác giả Stanton E.Samenow đã cung cấp cho độc giả một ấn bản cập nhật hoàn toàn về tác phẩm kinh điển của mình, bao gồm những sự nhận thức mới mẻ về tội ác đang được chú ý ngày nay, từ sự rình rập và bạo lực gia đình đến tội phạm cổ cồn và chính trị khủng bố. Ông đã từng có ba thập kỷ làm việc với tội phạm khẳng định lại lập luận của mình rằng các yếu tố như nghèo đói, ly hôn và bạo lực trên phương tiện truyền thông không gây ra tội phạm. Đúng hơn, như các tài liệu của Samenow ở đây, tất cả tội phạm đều có chung một suy nghĩ đặc biệt - thường thấy rõ trong thời thơ ấu - khác hẳn với suy nghĩ của một công dân có trách nhiệm.',
        220.0,
      ),
      Book(
        '33',
        '9',
        'Tâm lý',
        'Tình Cờ Gặp Hạnh Phúc – Daniel Gilbert',
        DateTime(2019, 3, 23),
        'assets/images/sach33.jpg',
        6.3,
        630,
        'Nằm trong danh sách những cuốn sách tâm lý học hay nhất của Dan Ariely, Phi Lý Trí có sức hấp dẫn đặc biệt và đầy cảm hứng. Nó buộc người đọc phải suy nghĩ kỹ hơn về tất cả những hành vi, những sai lầm của mình để sống hợp lý và tốt đẹp hơn.',
        220.0,
      ),
     Book(
        '34',
        '9',
        'Tâm lý',
        'Đi Tìm Lẽ Sống – Viktor Emil Frankl',
        DateTime(2019, 3, 23),
        'assets/images/sach34.jpg',
        6.4,
        640,
        'Cuốn hồi ký của bác sĩ tâm thần Viktor Frankl đã làm say lòng biết bao thế hệ độc giả với những mô tả về cuộc sống trong các trại tử thần của Đức Quốc xã và những bài học để tồn tại về mặt tinh thần. Từ năm 1942 đến năm 1945, Frankl lao động trong bốn trại khác nhau, bao gồm cả trại Auschwitz, trong khi cha mẹ, anh trai và người vợ đang mang thai của ông đã chết.',
        220.0,
      ),
      Book(
        '35',
        '8',
        'Truyện',
        '999 Lá Thư Gửi Cho Chính Mình - Những Lá Thư Ấn Tượng Nhất (Phiên Bản Song Ngữ Trung - Việt)',
        DateTime(2019, 3, 23),
        'assets/images/sach35.jpg',
        6.5,
        650,
        'Đã bao lâu rồi bạn chưa ngồi xuống viết những dòng nhật ký, đã bao lâu rồi bạn chưa tự gửi cho mình một lá thư viết ra những điều bạn mong muốn, viết ra những ước mơ còn dang dở, viết ra những khó khăn bạn đã hoặc đang phải trải qua và cũng không quên động viên, cổ vũ chính mình của hiện tại, nhắn nhủ đến chính mình của tương lai…',
        220.0,
      ),
      Book(
        '36',
        '8',
        'Truyện',
        'Từ Điển Tiếng “Em” - Tái Bản 2021',
        DateTime(2019, 3, 23),
        'assets/images/sach36.jpg',
        6.6,
        660,
        'Nói đến “từ điển”, xưa nay chúng ta đều nghĩ về một bộ sách đồ sộ, giải thích ý nghĩa, cách dùng, dịch, cách phát âm, và thường kèm theo các ví dụ về cách sử dụng từ đó.',
        220.0,
      ),
      Book(
        '37',
        '8',
        'Truyện',
        'Tạm Biệt Tôi Của Nhiều Năm Về Trước',
        DateTime(2019, 3, 23),
        'assets/images/sach37.jpg',
        6.7,
        670,
        'Chỉ khi bạn đi về phía ánh sáng, chiếc bóng mới hắt về phía sau. Đừng tự giam cầm mình trong quá khứ, hãy làm gì đó để bản thân cảm thấy tốt hơn. Rồi mọi chuyện cũng sẽ qua, mọi vết thương đều sẽ lành lại',
        220.0,
      ),
      Book(
        '38',
        '8',
        'Truyện',
        'Chúng Ta Rồi Sẽ Hạnh Phúc, Theo Những Cách Khác Nhau',
        DateTime(2019, 3, 23),
        'assets/images/sach38.jpg',
        6.8,
        680,
        'CHÚNG TA RỒI SẼ HẠNH PHÚC, THEO NHỮNG CÁCH KHÁC NHAU là một lời nhắn nhủ của tác giả Thảo Thảo đến tất cả mọi người rằng mỗi chúng ta đều là một cá thể duy nhất trong vũ trụ bao la rộng lớn, đừng bao giờ cho người khác quyền mang lại niềm vui hay nỗi buồn cho bạn. Hãy sống với những gì bạn muốn, làm nhũng gì bạn cho là đúng, bởi nếu cứ sống vì người khác, bạn sẽ đánh mất những-gì-đặc-biệt-nhất của bản thân mình.',
        220.0,
      ),
      Book(
        '39',
        '8',
        'Truyện',
        'Những Đêm Không Ngủ Những Ngày Chậm Trôi',
        DateTime(2019, 3, 23),
        'assets/images/sach39.jpg',
        6.8,
        680,
        'Cuốn sách là tập hợp những câu chuyện có thật của những số phận khác nhau đang gặp phải các vấn đề về tâm lý: trầm cảm, rối loạn lo âu, rối loạn lưỡng cực… và những người đang học tập và làm việc trong ngành tâm lý học. ',
        220.0,
      ),
      Book(
        '40',
        '8',
        'Truyện',
        'Phụ Nữ Hiểu Biết Sẽ Có Cuộc Sống Đẳng Cấp Hơn',
        DateTime(2019, 3, 23),
        'assets/images/sach40.jpg',
        7.0,
        700,
        'Tôi vẫn luôn cho rằng, phụ nữ thời nay coi trọng đàn ông, tình yêu và hôn nhân, đến mức không ngừng bám víu vào thái độ của đàn ông đối với mình. Người đàn ông như vậy rốt cuộc có đáng để lấy làm chồng không. Nói thực lòng, nếu bạn dồn hết những tâm tư đã đặt vào đàn ông để trau dồi cho bản thân, thì bạn đã trở thành nữ thần lâu rồi.',
        220.0,
      ),
      Book(
        '41',
        '8',
        'Truyện',
        'Điều Đẹp Nhất Có Khi Là Buông Tay (Tái Bản)',
        DateTime(2019, 3, 23),
        'assets/images/sach41.jpg',
        7.1,
        710,
        'Thought Catalog là một nhóm tác giả nổi tiếng tại Mỹ, với những câu chuyện giúp bạn đi sâu hơn vào phần yếu mềm bên trong trái tim của mình, ôm ấp nỗi cô đơn và khiến bạn mạnh mẽ rời bỏ những điều, những người làm bạn đau.',
        220.0,
      ),
      Book(
        '42',
        '8',
        'Truyện',
        'Có Một Ngày, Bố Mẹ Sẽ Già Đi',
        DateTime(2019, 3, 23),
        'assets/images/sach42.jpg',
        7.2,
        720,
        'Bạn khát vọng cuộc sống khởi sắc, không còn quẫn bách giật gấu vá vai. Bạn khát vọng sự nghiệp tiến triển, như thế mới không uổng bao năm vất vả tăng ca bất kể gió mưa. Bạn khát vọng con cái của mình về sau có thể lớn lên vui vẻ khỏe mạnh, đạt được thành tích đáng tự hào, vươn lên trong môi trường cạnh tranh quyết liệt… Nhưng bạn lại vô tình đặt một khát vọng khác nằm sâu trong tâm hồn xuống vị trí dưới cùng, khát vọng này chính là hy vọng bố mẹ đừng vội già đi.',
        220.0,
      ),
      Book(
        '1',
        '1',
        'Chính trị',
        'Tony Blair – Hành Trình Chính Trị Của Tôi',
        DateTime(2019, 3, 23),
        'assets/images/sach1.gif',
        3.4,
        121,
        'Tony Blair là một trong những chính trị gia nổi tiếng nhất thế kỷ XX. Ông trở thành thủ tướng Anh năm 1997, thay thủ tướng John Major và kết thúc giai đoạn 18 năm cầm quyền của đảng Bảo thủ. Cho đến nay, ông là thủ tướng lâu năm nhất của đảng Lao động và là người duy nhất dẫn dắt đảng này chiến thắng ba cuộc tổng tuyển cử kề nhau.',
        220.0,
      ),
      Book(
        '2',
        '1',
        'Chính trị',
        'Bush Và Quyền Lực Nước Mỹ',
        DateTime(2019, 3, 23),
        'assets/images/sach2.jpg',
        3.2,
        320,
        'Nước Mỹ dưới thời của Tổng thống George Walker Bush đã trải qua không ít biến cố đau thương và đánh dấu sự thay đổi của nước Mỹ hùng mạnh. Châm ngòi cho hành trình lịch sử chính là ngày 11/09, khi tòa tháp đôi thương mại tại New York bị máy bay đâm trong một kế hoạch trả đũa của khủng bố. Đây là đòn giáng xuống sự tự hào của nước Mỹ, và Tổng thống Bush đã quyết định hành động mạnh mẽ nhằm loại trừ hoàn toàn khủng bố. Nhưng phương châm của ông bị đánh giá là mang tính cực đoan “Không theo ta là chống lại ta, phải tiêu diệt” và chính điều này chính quyền Bush đã dần dần đánh mất sự ủng hộ của thế giới. Tiếp sau đó là hàng loạt cuộc tấn công nhằm vào khủng bố tại Iraq cũng như loại trừ Saddam Hussein.w',
        220.0,
      ),
      Book(
        '3',
        '1',
        'Chính trị',
        'Chính Trị Thế Giới Sau Năm 1945',
        DateTime(2019, 3, 23),
        'assets/images/sach3.jpg',
        3.3,
        330,
        'Thế chiến thứ hai như là cuộc đụng độ tư tưởng, kết thúc bằng thất bại của chủ nghĩa phát xít, mở đường cho mối xung đột trầm trọng giữa nền dân chủ phương Tây và chủ nghĩa Cộng sản. Nhưng xét cho cùng, đây là cuộc chiến xuất phát từ tham vọng của các siêu cường quốc, mà thất bại của Đức và Nhật đã đẩy Hoa Kỳ và Liên Xô lên vị trí quyền lực hàng đầu, để rồi hai nước bị chia rẽ sâu sắc về triết lý chính trị và kinh tế đâm ra dè chừng, e sợ lẫn nhau. Chính nỗi nhiều sợ này là thủ phạm thực sự của Chiến tranh lạnh kéo dài cả nửa sau thế kỷ 20, thể hiện mâu thuẩn đối kháng sâu sắc trên bình diện tư tưởng mang tính toàn cầu.',
        220.0,
      ),
      Book(
        '4',
        '1',
        'Chính trị',
        'Chế Độ Chính Trị Trung Quốc',
        DateTime(2019, 3, 23),
        'assets/images/sach4.gif',
        3.4,
        340,
        'Chế độ chính trị Trung Quốc hiện nay bao gồm: Bộ máy Nhà nước, Chế độ Bầu cử, Chế độ Đại hội đại biểu Nhân dân, Chế độ Chủ tịch nước, Chế độ Hành chính, Chế độ Tư pháp, Chế độ Quân sự, Chế độ Hợp tác Đa đảng và Hiệp thương chính trị, Chế độ Dân chủ cơ sở Quyển sách này sẽ giới thiệu lần lượt từng chế độ của Trung Quốc đương đại và những cải cách thể chế chính trị.',
        220.0,
      ),
      Book(
        '5',
        '12',
        'Pháp luật',
        'Bàn Về Tinh Thần Pháp Luật',
        DateTime(2019, 3, 23),
        'assets/images/sach5.png',
        3.5,
        350,
        'Bàn về tinh thần pháp luật là tuyệt tác triết học của Montesquieu, là một trong những tác phẩm vĩ đại trong lịch sử triết học chính trị và trong lịch sử luật học. Mục đích cuốn sách, như chính tác giả đã nêu, là: Trình bày những nguyên nhân quyết định nền pháp lý cho mỗi quốc gia; trình bày sự phù hợp cần thiết giữa luật lệ và chế độ cai trị của một nước; trình bày những quan hệ giữa các luật lệ với nhau. Ông đã phải mất gần 20 năm cho tác phẩm này.',
        220.0,
      ),
      Book(
        '6',
        '12',
        'Pháp luật',
        'Bàn Về Khế Ước Xã Hội',
        DateTime(2019, 3, 23),
        'assets/images/sach6.png',
        3.6,
        360,
        'Về mục đích cuốn sách, tác giả viết: “Tôi muốn tìm xem trong trật tự dân sự có hay không một số quy tắc cai trị chính đáng, vững chắc, biết đối đãi với con người như con người. Và có hay không luật pháp đúng với những ý nghĩa chân thực của nó”. Với luận văn này, J. J. Rousseau muốn “gắn liền cái mà luật pháp cho phép làm với cái mà lợi ích thúc đẩy phải làm, khiến cho công lý và lợi ích không tách rời nhau”.',
        220.0,
      ),
      Book(
        '7',
        '12',
        'Pháp luật',
        'Cộng hòa',
        DateTime(2019, 3, 23),
        'assets/images/sach7.png',
        3.7,
        370,
        'Cuốn sách được xem là cột mốc lớn của triết học phương Tây. Tác phẩm được trình bày dưới dạng đối thoại giữa Plato và những người khác. Mặc dù chủ đề chính là về một nhà nước lý tưởng nhưng nó cũng xoay quanh giáo dục, tâm lý, đạo đức và chính trị. Trong các đoạn chính của Cộng hòa, Plato sử dụng những huyền thoại để khám phá bản chất tự nhiên của thực tế, truyền đạt cái nhìn về sự tiên đoán của con người và vai trò của triết học trong việc thiết lập tự do. Ông tưởng tượng ra một cái hang mà những con người bị xiềng xích từ khi mới sinh ra làm bạn với cái bóng của mình và mang họ đến thực tế. Vai trò của triết học, cụ thể là những gì Plato gọi là biện chứng, là đưa con người ra khỏi cái bóng và hướng bản thân họ tới thực tế. Đây là bản chất của việc theo đuổi sự khôn ngoan mà không có nhà nước lý tưởng nào không làm. Độc giả hiện đại có thể đồng ý với mọi điều Plato nói, cũng như lập luận chặt chẽ, cái nhìn đầy chất thơ vẫn có sức mạnh trong việc kích thích và thách thức. Sức mạnh lâu dài này đã làm của Cộng hòa trở thành một trong những nền tảng của văn hóa phương Tây.',
        220.0,
      ),
      Book(
        '8',
        '2',
        'Khoa học công nghệ',
        'Lược Sử Vạn Vật - A Short History Of Nearly Everything',
        DateTime(2019, 3, 23),
        'assets/images/sach8.jpg',
        3.8,
        380,
        'Với cuốn sách này, người đọc sẽ biết được những giới hạn trong tri thức của con người về vũ trụ và cả về chính trái đất. Đây là cuốn sách khoa học phổ thông bán chạy nhất nước Anh năm 2005 với hơn 300.000 bản in. Nhà phê bình người Anh, Craig Brown thậm chí đã nhận xét rằng tác phẩm này xứng đáng bán được 500.000.000.000 cuốn (theo cách nói của chính Bryson, "bằng với số proton có trong một dấu chấm câu").William McGuire "Bill" Bryson, tác giả cuốn sách Lược sử vạn vật - A Short History of Nearly Everything sinh năm 1951, là tác giả nổi tiếng hàng đầu trong thể loại non-fiction ở Bắc Mỹ, với vô số người hâm mộ trên khắp thế giới.',
        220.0,
      ),
      Book(
        '9',
        '2',
        'Khoa học công nghệ',
        'Khoa Học Khám Phá - Lược Sử Thời Gian (Tái Bản 2022)',
        DateTime(2019, 3, 23),
        'assets/images/sach9.jpg',
        3.9,
        390,
        'Tò mò là một trong những phẩm chất bẩm sinh vô cùng quan trọng của chúng ta, và những vấn đề như Bản chất của vũ trụ là gì? Vũ trụ từ đâu ra? Chúng ta đến từ đâu và đóng vai trò gì trong vũ trụ? Có giới hạn cho sự nhận thức của con người không?... là những câu hỏi mà biết bao nhiêu thế hệ con người đã đặt ra dưới dạng này hoặc dạng khác từ khi bắt đầu biết nhận thức và suy ngẫm về thế giới này. Tất cả những vấn đề được nên ra trong tác phẩm Lược sử thời gian như Vũ trụ giãn nở, Lỗ đen, Nguồn gốc và số phận của vũ trụ, Mũi tên thời gian… đều là mong muốn của tác giả để phần nào trả lời được những câu hỏi đó, và hướng tới việc giải thích các giai đoạn lịch sử của toàn bộ vũ trụ.',
        220.0,
      ),
    
      Book(
        '11',
        '3',
        'Kinh tế',
        'Những cuộc phiêu lưu trong kinh doanh',
        DateTime(2019, 3, 23),
        'assets/images/sach11.jpg',
        4.1,
        410,
        'Tác phẩm này của Brooks nhắc nhở chúng ta các nguyên tắc điều hành một doanh nghiệp vững mạnh và tạo ra các giá trị bền vững như yếu tố con người luôn đóng vai trò quan trọng trong mọi hoạt động kinh doanh? Dù có sản phẩm chất lượng hay kế hoạch sản xuất và truyền thông xuất sắc đến đâu chăng nữa, bạn vẫn cần những con người thích hợp để chỉ đạo và thực hiện kế hoạch đó',
        220.0,
      ),
      Book(
        '12',
        '3',
        'Kinh tế',
        'Lược Sử Kinh Tế Học',
        DateTime(2019, 3, 23),
        'assets/images/sach12.jpg',
        4.2,
        420,
        'Kinh tế học hóa ra không chỉ là một lĩnh vực tri thức cao siêu, xa vời dành riêng cho những nhà kinh tế học, chính khách hay doanh nhân, nó hiện diện trong mọi quyết định lớn nhỏ của đời sống. Nhận thức được tầm quan trọng của những hiểu biết kinh tế học căn bản đối với con người trong xã hội đương đại nhiều biến động khó lường, Niall Kishtainy đã trang bị cho độc giả đại chúng một “công cụ” sắc bén, hữu ích mà lại rất dễ dàng tiếp cận',
        220.0,
      ),
      Book(
        '13',
        '3',
        'Kinh tế',
        'Doanh Nghiệp Của Thế Kỷ 21',
        DateTime(2019, 3, 23),
        'assets/images/sach13.jpg',
        4.3,
        430,
        'Robert Toru Kiyosaki sẽ đưa ra lý do tại sao chúng ta cần phải tạo dựng doanh nghiệp riêng của mình (bao gồm việc thay đổi loại hình doanh nghiệp, thay đổi tư duy làm giàu đúng đắn và cách thức tìm kiếm phương tiện xây dựng doanh nghiệp phù hợp với bản thân mỗi người). Tác giả còn cho bạn đọc biết cách thức tìm kiếm những gì mình cần để phát triển doanh nghiệp hoàn hảo, nhưng để doanh nghiệp của mình phát triển thì mình cũng sẽ phải phát triển theo.',
        220.0,
      ),
      Book(
        '14',
        '3',
        'Kinh tế',
        'Lời Thú Tội Mới Của Một Sát Thủ Kinh Tế',
        DateTime(2019, 3, 23),
        'assets/images/sach14.jpg',
        4.4,
        440,
        'Trong Lời Thú Tội Mới Của Một Sát Thủ Kinh Tế, John Perkins kể về sự giằng xé nội tâm mà ông đã từng trải qua để từ một người đầy tớ trung thành với đế chế trở thành ngưởi bênh vực hết mình cho quyền lợi của những người bị áp bức. Được cơ quan An ninh quốc gia Hoa Kỳ bí mật tuyển và trả lương qua một hãng tư vấn quốc tế, ông đã đi khắp nơi trên thế giới - đến Indonesia, Panama, Ecuado, Colombia, Arab Saudi, Iran và những địa điểm mang tầm chiến lược khác. Núp dưới danh nghĩa xoá đói giảm nghèo, công việc của ông trên thực tế là thực thi các chính sách nhằm phục vụ lợi ích của chủ nghĩa tập đoàn Mỹ (một liên minh giữa chính phủ, các ngân hàng và các tập đoàn). Chính những chính sách này đã gây nên sự chia rẽ giữa các quốc gia, cuối cùng dẫn tới sự kiện ngày 11/9 và khiến cho làng sóng chống đối Mỹ ngày càng gia tăng.',
        220.0,
      ),
      Book(
        '15',
        '4',
        'Văn học',
        'Giết con chim nhại',
        DateTime(2019, 3, 23),
        'assets/images/sach15.jpg',
        4.5,
        450,
        'Giết con chim nhại (nguyên tác tiếng Anh: To Kill a Mockingbird) là cuốn tiểu thuyết của Harper Lee; đây là cuốn tiểu thuyết rất được yêu chuộng, thuộc loại bán chạy nhất thế giới với hơn 10 triệu bản. Cuốn tiểu thuyết được xuất bản vào năm 1960 và đã giành được giải Pulitzer cho tác phẩm hư cấu năm 1961. Nội dung tiểu thuyết dựa vào cuộc đời của nhiều bạn bè và họ hàng tác giả, nhưng tên nhân vật đã được thay đổi. Tác giả cho biết hình mẫu nhân vật Jean Louise "Scout" Finch, người dẫn truyện, được xây dựng dựa vào chính bản thân mình.',
        220.0,
      ),
      Book(
        '16',
        '4',
        'Văn học',
        'Tuổi thơ dữ dội',
        DateTime(2019, 3, 23),
        'assets/images/sach16.jpg',
        4.6,
        460,
        'Cuốn truyện có hệ thống nhân vật khá giống "Những ngày khói lửa" và một vài truyện ngắn khác, khiến người đọc cảm giác là có nhiều tác phẩm khác nhau trong thời kỳ này cùng viết về một nhóm nhân vật có thật. Năm 1988, cuốn tiểu thuyết Tuổi thơ dữ dội của Phùng Quán được xuất bản và nhận Giải thưởng Văn học Thiếu nhi của Hội Nhà văn Việt Nam hai năm sau đó và đã được dựng thành phim.',
        220.0,
      ),
      Book(
        '17',
        '4',
        'Văn học',
        'Tiếng chim hót trong bụi mận gai',
        DateTime(2019, 3, 23),
        'assets/images/sach17.jpg',
        4.7,
        470,
        'Cuốn tiểu thuyết xây dựng như truyện sử biên gia đình, tác giả tập trung vào những xung đột tâm lý - đạo đức nhiều hơn là những vấn đề giai cấp-xã hội. Các nhân vật tuy chịu ảnh hưởng của hoàn cảnh nhưng chủ yếu là ứng xử theo tính cách riêng của mình nhiều hơn. Trong số nhiều nhân vật, nổi bật hơn cả là ba nhân vật: Fiôna, Meggie, con gái bà và cha đạo Ralph. Meggie có thể coi là nhân vật trung tâm của tác phẩm. Trong tiểu thuyết có nhiều đề tài, nhiều mối tình, song tất cả đều phục vụ câu chuyện chính, mối tình lớn lao, trong sáng của Meggie và cha Ralph.',
        220.0,
      ),
      Book(
        '18',
        '4',
        'Văn học',
        'Không gia đình',
        DateTime(2019, 3, 23),
        'assets/images/sach18.jpg',
        4.8,
        480,
        'Em đã lao động lấy mà sống, lúc đầu dưới quyền điều khiển của một ông già từng trải và đạo đức, cụ Vitalis, về sau thì tự lập và không những lo cho mình, còn bảo đảm việc biểu diễn và sinh sống cho cả một gánh hát rong. Đã có khi em và cả đoàn lang thang suốt mấy ngày không có chút gì trong bụng. Đã có khi em bị lụt ngầm chôn trong giếng mỏ mười mấy ngày đêm. Đã có khi em mắc oan, bị giải ra trước tòa án và bị ở tù. Và cũng có khi em được nuôi nấng đàng hoàng, no ấm. Nhưng dù ở đâu, trong cảnh ngộ nào, em vẫn noi theo nếp rèn dạy của ông già Vitalis giữ phẩm chất làm người, nghĩa là ngay thẳng, gan dạ, tự trọng, thương người, ham lao động, không ngửa tay xin xỏ, không dối trá, gian giảo, nhớ ơn nghĩa, luôn luôn muốn làm người có ích.',
        220.0,
      ),
      Book(
        '19',
        '5',
        'Nghệ thuật',
        'Nghệ Thuật – Khái Lược Những Tư Tưởng Lớn (DK)',
        DateTime(2019, 3, 23),
        'assets/images/sach19.jpg',
        4.9,
        490,
        'Bằng ngôn từ giản dị, Nghệ thuật – Khái lược những tư tưởng lớn của sẽ đưa bạn xuyên qua lý thuyết và lịch sử nghệ thuật bằng những hình ảnh về các tác phẩm vĩ đại nhất trên thế giới cùng nhiều sơ đồ hóm hỉnh giúp khám phá các ý tưởng đằng sau. Từ tượng phồn thực thời tiền sử đến sắp đặt video đương đại, đây là cuốn sách vỡ lòng hoàn hảo về nghệ thuật thế giới.',
        220.0,
      ),
      Book(
        '20',
        '5',
        'Nghệ thuật',
        'LEONARDO DA VINCI: Cuộc đời và tác phẩm qua 500 hình ảnh (Rosalind Ormiston)',
        DateTime(2019, 3, 23),
        'assets/images/sach20.png',
        5.0,
        500,
        'Qua cuốn sách này, bạn có cái nhìn toàn diện về cuộc đời và các tác phẩm của Leonardo da Vinci, về đời sống cá nhân của người nghệ sĩ, cũng như các ảnh hưởng của ông đối với nghệ thuật và bối cảnh lịch sử ở Ý thời Phục hưng. Hơn nữa, bạn còn được khảo sát các tác phẩm quan trọng của Leonardo bao gồm các bức tranh và các phát minh tuyệt vời được minh họa tuyệt đẹp với 500 hình ảnh nổi bật.',
        220.0,
      ),
      Book(
        '21',
        '6',
        'Văn hóa xã hội',
        'Việt Nam phong tục',
        DateTime(2019, 3, 23),
        'assets/images/sach21.png',
        5.1,
        510,
        'một sách về văn hóa nghiên cứu khá kĩ lưỡng và toàn diện về phong tục, tập quán của người Việt, từ phong tục trong gia đình, làng xã đến phong tục quốc gia, xã hội được viết với văn phong hiện đại dù vẫn chịu ảnh hưởng của lối viết biền ngẫu đăng đối trong văn học cổ. Mỗi chương, mục đều được tác giả trình bày và diễn giải khúc chiết, ngắn gọn, rõ ràng với quan điểm khá tân tiến so với những người cùng thời.',
        220.0,
      ),
      Book(
        '22',
        '6',
        'Văn hóa xã hội',
        'Bản sắc văn hóa vùng ở Việt Nam',
        DateTime(2019, 3, 23),
        'assets/images/sach22.png',
        5.2,
        520,
        'Văn hóa vùng hình thành trên cơ sở giao lưu, giao tiếp lâu đời giữa các dân tộc có sự tương đồng về kinh tế, xã hội, cùng sinh sống trong một vùng địa lý nhất định, văn hóa vùng đóng vai trò như là bước trung gian, như cái cầu nối, để từ văn hóa tộc người, thai nghén và hình thành văn hóa quốc gia; và ngược lại, từ văn hóa quốc gia, tác động trở lại các xu hướng phát triển của văn hóa tộc người, văn hóa vùng. Cuốn sách 09 chương giúp ta có cái nhìn tổng quan về bản sắc văn hoá đất nước ta',
        220.0,
      ),
      Book(
        '24',
        '7',
        'Lịch sử',
        'Việt Nam Sử Lược',
        DateTime(2019, 3, 23),
        'assets/images/sach24.jpg',
        5.4,
        540,
        'Đây là cuốn sách sử Việt đầu tiên thoát khỏi truyền thống viết sử theo lối biên niên, cương mục, ngôn từ khó hiểu của sách sử Việt thời phong kiến, nên được rất nhiều độc giả đón nhận. Tuy nhiên, về mặt chuyên môn, do biên soạn trong thời gian quá ngắn, lại chỉ do một mình Trần Trọng Kim biên soạn nên sách cũng có nhiều chi tiết sai sót, gây hiểu lầm cho người đọc.',
        220.0,
      ),
      Book(
        '25',
        '7',
        'Lịch sử',
        'Các Triều Đại Việt Nam',
        DateTime(2019, 3, 23),
        'assets/images/sach25.jpg',
        5.5,
        550,
        'trình bày rất chi tiết về các triều đại của Việt Nam. Từ “Nước Việt Nam – Quốc hiệu” đến thời kỳ bắt đầu thuộc Pháp. Đây được đánh giá là một trong những cuốn sách viết đầy đủ nhất về sự mở đầu kế tục của các triều đại, các đời vua trong lịch sử dân tộc.',
        220.0,
      ),
      Book(
        '26',
        '10',
        'Tôn giáo',
        'Không Diệt Không Sinh Đừng Sợ Hãi (Tái Bản 2022)',
        DateTime(2019, 3, 23),
        'assets/images/sach26.jpg',
        5.6,
        560,
        'Bụt có cái hiểu rất khác về cuộc đời. Ngài hiểu rằng sống và chết chỉ là những ý niệm không có thực. Coi đó là sự thực, chính là nguyên do gây cho chúng ta khổ não. Bụt dạy không có sinh, không có diệt, không tới cũng không đi, không giống nhau cũng không khác nhau, không có cái ngã thường hằng cũng không có hư vô. Chúng ta thì coi là Có hết mọi thứ. Khi chúng ta hiểu rằng mình không bị hủy diệt thì chúng ta không còn lo sợ. Đó là sự giải thoát. Chúng ta có thể an hưởng và thưởng thức đời sống một cách mới mẻ.',
        220.0,
      ),
      Book(
        '27',
        '10',
        'Tôn giáo',
        'Hành Trình Về Phương Đông (Tái Bản 2021)',
        DateTime(2019, 3, 23),
        'assets/images/sach27.jpg',
        5.7,
        570,
        'ành Trình Về Phương Đông kể về những trải nghiệm của một đoàn khoa học gồm các chuyên gia hàng đầu của Hội Khoa Học Hoàng Gia Anh được cử sang Ấn Độ nghiên cứu về huyền học và những khả năng siêu nhiên của con người. Suốt hai năm trời rong ruổi khắp các đền chùa Ấn Độ, diện kiến nhiều pháp thuật, nhiều cảnh mê tín dị đoan, thậm chí lừa đào… của nhiều pháp sư, đạo sĩ… họ được tiếp xúc với những vị chân tu thông thái sống ẩn dật ở thị trấn hay trên rặng Tuyết Sơn. Nhờ thế, họ được chứng kiến, trải nghiệm, hiểu biết sâu sắc về các khoa học cổ xức và bí truyền của văn hóa Ấn Độ như yoga, thiền định, thuật chiêm tinh, các phép dưỡng sinh và chữa bệnh, những kiến thức về nhân duyên, nghiệp báo, luật nhân quả, cõi sống và cõi chết…',
        220.0,
      ),
      Book(
        '28',
        '11',
        'Thiếu nhi',
        'Hoàng Tử Bé (Tái Bản)',
        DateTime(2019, 3, 23),
        'assets/images/sach28.jpg',
        5.8,
        580,
        'Hoàng tử bé được viết ở New York trong những ngày tác giả sống lưu vong và được xuất bản lần đầu tiên tại New York vào năm 1943, rồi đến năm 1946 mới được xuất bản tại Pháp. Không nghi ngờ gì, đây là tác phẩm nổi tiếng nhất, được đọc nhiều nhất và cũng được yêu mến nhất của Saint-Exupéry. Cuốn sách được bình chọn là tác phẩm hay nhất thế kỉ 20 ở Pháp, đồng thời cũng là cuốn sách Pháp được dịch và được đọc nhiều nhất trên thế giới. Với 250 ngôn ngữ dịch khác nhau kể cả phương ngữ cùng hơn 200 triệu bản in trên toàn thế giới, Hoàng tử bé được coi là một trong những tác phẩm bán chạy nhất của nhân loại. ',
        220.0,
      ),
      Book(
        '29',
        '11',
        'Thiếu nhi',
        'Totto-Chan Bên Cửa Sổ (Tái Bản 2019)',
        DateTime(2019, 3, 23),
        'assets/images/sach29.jpg',
        5.9,
        590,
        'Totto-chan bên cửa sổ là cuốn sách gối đầu giường của nhiều thế hệ trẻ em trên toàn thế giới suốt ba mươi năm nay. Sau khi xuất bản lần đầu vào năm 1981, cuốn sách đã gây được tiếng vang lớn không chỉ ở Nhật Bản mà còn trên toàn thế giới. Tính đến năm 2001, tổng số bản sách bán ra ở Nhật đã lên đến 9,3 triệu bản, trở thành một trong những cuốn sách bán chạy nhất trong lịch sử ngành xuất bản nước này. Cuốn sách đã được dịch ra 33 thứ tiếng khác nhau, như Anh, Pháp, Đức, Hàn Quốc, Trung Quốc…Khi bản tiếng Anh của Totto-chan được xuất bản tại Mỹ, tờ New York Times đã đăng liền hai bài giới thiệu trọn trang, một “vinh dự” hầu như không tác phẩm nào có được.',
        220.0,
      ),
      
      // Book(
      //   '43',
      //   'typeId',
      //   'type',
      //   'name',
      //   DateTime(2019, 3, 23),
      //   'assets/images/book1.jpg',
      //   'score',
      //   8989,
      //   'review',
      //   220.0,
      // ),
      // Book(
      //   '39',
      //   'typeId',
      //   'type',
      //   'name',
      //   DateTime(2019, 3, 23),
      //   'assets/images/book1.jpg',
      //   'score',
      //   8989,
      //   'review',
      //   220.0,
      // ),
      // Book(
      //   '39',
      //   'typeId',
      //   'type',
      //   'name',
      //   DateTime(2019, 3, 23),
      //   'assets/images/book1.jpg',
      //   'score',
      //   8989,
      //   'review',
      //   220.0,
      // ),
      // Book(
      //   '39',
      //   'typeId',
      //   'type',
      //   'name',
      //   DateTime(2019, 3, 23),
      //   'assets/images/book1.jpg',
      //   'score',
      //   8989,
      //   'review',
      //   220.0,
      // ),
      // Book(
      //   '39',
      //   'typeId',
      //   'type',
      //   'name',
      //   DateTime(2019, 3, 23),
      //   'assets/images/book1.jpg',
      //   'score',
      //   8989,
      //   'review',
      //   220.0,
      // ),
      
    ];
  }
}
